### ISSUE TITLE
Doesn't honor ->readonly()

### ISSUE THREAD

**Issue by MikeCraig418** [nalingia/nova-secret-field#3] opened 2020-05-04 19:02 UTC
Sometimes secrets should change....

```
NovaSecretField::make('API Key', 'api_key')->readonly(),
```

Great plugin, btw! I'll give you 5 stars on Nova Packages if you can get these issues taken care of.

**Comment by nalingia** [comment] 2020-05-05 07:12
Hi again @949mac ,
thanks for your reporting.
The issue is going to be fixed on next patch release (1.0.5).

**Comment by nalingia** [comment] 2020-05-05 12:11
Fixed in 1.0.5

**Closed as completed** 2020-05-05 12:10 UTC
Labels: bug
